/* =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */
/*  »Project«   Teikitu Gaming System (TgS) (∂)
    »File«      TgS Kernel [GPU] - Constants.h
    »Author«    Andrew Aye (mailto: teikitu@andrewaye.com, https://www.andrew.aye.page)
    »Version«   5.20 | »GUID« DE461472-5528-4A5B-A7F4-09CCAD73387B */
/*  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
/*  Copyright: © 2002-2025, Andrew Aye.  All Rights Reserved.
    This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. To view a copy of this license,
    visit http://creativecommons.org/licenses/by-nc-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA. */
/* =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- */
#if !defined(TGS_KERNEL_GPU_CONSTANTS_H) && defined(TgBUILD_FEATURE__GRAPHICS)
#define TGS_KERNEL_GPU_CONSTANTS_H

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

#include "TgS KERNEL/TgS Kernel [GPU] - Resource [HLSL] [Constants].h"
#include TgHEADER_GRAPHCIS(TgS KERNEL/TgS,Kernel [GPU] - Constants.h)


/* == Kernel ===================================================================================================================================================================== */

/* -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.--.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-. */
/*  Configuration                                                                                                                                                                  */
/* -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.--.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-. */

enum { KTgKN_GPU_MAX_HOST_CONTEXT                   =      1,   /**< Maximum number of Host/CPU resource contexts (one per host/cpu memory controller). */
       KTgKN_GPU_MAX_DEVC_CONTEXT                   =      4,   /**< Maximum number of GPU devices allowed. */
       KTgKN_GPU_MAX_EXEC_CONTEXT                   =      4,   /**< Maximum number of GPU execute contexts allowed (one per node). */
       KTgKN_GPU_MAX_SWAP_CONTEXT                   =      9,   /**< Maximum number of GPU output (scan-out) devices. */

       KTgKN_GPU_MAX_PHYSICAL_DEVICE                =      8,   /**< Maximum number of GPU physical devices that can be enumerated. */
       KTgKN_GPU_MAX_PHYSICAL_DEVICE_NODE           =      2,   /**< Maximum number of GPU nodes per physical device that can be enumerated. */
       KTgKN_GPU_MAX_PHYSICAL_DEVICE_NAME           =    128,   /**< Maximum length of physical device name | description. */
       KTgKN_GPU_MAX_OUTPUT                         =     64,   /**< Maximum number of GPU output (scan-out) devices per adapter than can be enumerated. */
       KTgKN_GPU_MAX_OUTPUT_NAME                    =     32,   /**< Maximum name stored for each output device. */

       KTgKN_GPU_MAX_BUFFER_IN_FLIP_CHAIN           =      3,   /**< Maximum latency of the system. For embedded devices this should match the exact desired configuration */
       KTgKN_GPU_MAX_EXEC_CONTEXT_COMMAND           =      3,

       KTgKN_GPU_MAX_SIMULTANEOUS_TARGET_COUNT      =      8,   /**< Maximum number of simultaneous images in a render target. */
       KTgKN_GPU_MAX_RENDER_TARGET                  =     32,   /**< Maximum number of render targets. */
       KTgKN_GPU_MAX_RENDER_TARGET_PER_FRAME        =     16,   /**< Maximum number of render targets / cameras in a single frame. */
       KTgKN_GPU_MAX_RENDER_TARGET_IMAGE            = KTgMACRO_KN_GPU_MAX_RENDER_TARGET_IMAGE, /**< Maximum number of render target images. */
       KTgKN_GPU_MAX_RENDER_DESC_PER_FRAME          =     64,   /**< Maximum number of render descriptor changes in a single frame. */

       KTgKN_GPU_MAX_VS                             =     16,   /**< Maximum number of vertex shaders. */
       KTgKN_GPU_MAX_TCS                            =      8,   /**< Maximum number of tessellation control shaders. */
       KTgKN_GPU_MAX_TES                            =      8,   /**< Maximum number of tessellation evaluation shaders. */
       KTgKN_GPU_MAX_GS                             =      8,   /**< Maximum number of geometry shaders. */
       KTgKN_GPU_MAX_TS                             =      8,   /**< Maximum number of task shaders. */
       KTgKN_GPU_MAX_MS                             =      8,   /**< Maximum number of mesh shaders. */
       KTgKN_GPU_MAX_FS                             =     32,   /**< Maximum number of fragment shaders. */
       KTgKN_GPU_MAX_CS                             =      8,   /**< Maximum number of compute shaders. */

       KTgKN_GPU_MAX_TX_IMG                         = KTgMACRO_KN_GPU_MAX_IMAGE, /**< Maximum number of 2D textures. */
       KTgKN_GPU_MAX_TX_CBE                         = KTgMACRO_KN_GPU_MAX_CUBE, /**< Maximum number of cube textures. */
       KTgKN_GPU_MAX_TX_VOL                         = KTgMACRO_KN_GPU_MAX_VOLUME, /**< Maximum number of volume textures. */

       KTgKN_GPU_MS__MAX                            =     32,

       KTgKN_GPU_MAX_MIP_LEVELS                     =     16,   /**< Maximum number of mip levels, a 64k texture can have 16 mip levels. */

       KTgKN_GPU_MAX_TX_IMG_INST                    = KTgMACRO_KN_GPU_MAX_IMAGE,
       KTgKN_GPU_MAX_TX_CBE_INST                    = KTgMACRO_KN_GPU_MAX_CUBE,
       KTgKN_GPU_MAX_TX_VOL_INST                    = KTgMACRO_KN_GPU_MAX_VOLUME,

       KTgKN_GPU_MAX_RELEASE_RESOURCE               =    256,

       KTgKN_GPU_RS_BIT__MAX_INDEX                  =     22,
       KTgKN_GPU_RS_BIT__SALT                       =     24,
       KTgKN_GPU_RS_BIT__LOAD                       =      1,
       KTgKN_GPU_RS_BIT__FREE                       =      1,
       KTgKN_GPU_RS_BIT__REFERENCE_COUNT            =     16,

       KTgKN_GPU_RSI_BIT__MAX_INDEX                 =     22,
       KTgKN_GPU_RSI_BIT__MAX_CONTEXT               =      2,
       KTgKN_GPU_RSI_BIT__SALT                      =     22,
       KTgKN_GPU_RSI_BIT__LOAD                      =      1,
       KTgKN_GPU_RSI_BIT__FREE                      =      1,
       KTgKN_GPU_RSI_BIT__REFERENCE_COUNT           =     16,
};

/* Maximum number of contexts is 2 bits == 4 */
TgCOMPILER_ASSERT( KTgKN_GPU_MAX_EXEC_CONTEXT <= (1 << KTgKN_GPU_RSI_BIT__MAX_CONTEXT), 0 );

/* Maximum number of instances per library is 22 bits == 4,194,303 */
/* Maximum number of references per resource is 18 bits == 262,143 */


/* -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.--.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-. */
/*  Public Constants                                                                                                                                                               */
/* -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.--.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-. */

/* List of memory locations and cache status */
typedef TgUINT_E64 ETgKN_GPU_RESOURCE_DESCRIPTOR;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_RESOURCE_DESCRIPTOR);

#define ETgKN_GPU_RESOURCE_DESCRIPTOR__INVALID 0ULL

#define ETgKN_GPU_RESOURCE_DESCRIPTOR__IGNORE_REF_COUNT (1ULL << 63)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__MAIN_MEMORY (1ULL << 62)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__ALLOCATOR_MASK (0xFULL << 60)

#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_1D (1ULL << 0)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_2D (1ULL << 1)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_2D_ARRAY (1ULL << 2)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_3D (1ULL << 3)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_CUBE (1ULL << 4)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_CUBE_ARRAY (1ULL << 5)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_MASK 0xFFULL

#define ETgKN_GPU_RESOURCE_DESCRIPTOR__RENDER_TARGET_TYPE_TEXTURE (1ULL << 8)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__DEPTH_STENCIL_TYPE_TEXTURE (1ULL << 9)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__UAV_TYPE_TEXTURE (1ULL << 10)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__UPLOAD_TYPE_TEXTURE (1ULL << 11)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__READBACK_TYPE_TEXTURE (1ULL << 12)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TEXTURE_TYPE_MASK (0xFFULL << 8)

#define ETgKN_GPU_RESOURCE_DESCRIPTOR__VERTEX_BUFFER (1ULL << 16)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__INDEX_BUFFER (1ULL << 17)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__UNIFORM_BUFFER (1ULL << 18)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__UNIFORM_BUFFER_DYNAMIC (1ULL << 19)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__STORAGE_BUFFER (1ULL << 20)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__STORAGE_BUFFER_DYNAMIC (1ULL << 21)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__UPLOAD_BUFFER (1ULL << 22)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__READBACK_BUFFER (1ULL << 23)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__INDIRECT_BUFFER (1ULL << 24)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__BUFFER_MASK (0xFFFFULL << 16)

#define ETgKN_GPU_RESOURCE_DESCRIPTOR__MEMORY_LOCAL (1ULL << 32)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__MEMORY_HOST_VISIBLE (1ULL << 33)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__MEMORY_HOST_COHERENT (1ULL << 34)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__MEMORY_PROPS_MASK (0xFULL << 32)

#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TRANSFER_SRC (1ULL << 36)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TRANSFER_DST (1ULL << 37)
#define ETgKN_GPU_RESOURCE_DESCRIPTOR__TRANSFER_PROPS_MASK (0xFULL << 36)



/* ---- GPU - Resource - Constants ----------------------------------------------------------------------------------------------------------------------------------------------- */

static const ETgKN_GPU_EXT_FORMAT KTgKN_GPU_EXT_FORMAT_RT_SCANOUT[] =  {
    ETgKN_GPU_EXT_FORMAT_R16G16B16A16_SFLOAT,
    ETgKN_GPU_EXT_FORMAT_A2B10G10R10_UNORM_PACK32,
    ETgKN_GPU_EXT_FORMAT_R8G8B8A8_UNORM,
    ETgKN_GPU_EXT_FORMAT_R8G8B8A8_SRGB,
    ETgKN_GPU_EXT_FORMAT_B8G8R8A8_UNORM,
    ETgKN_GPU_EXT_FORMAT_B8G8R8A8_SRGB,
};
enum { KTgKN_GPU_EXT_FORMAT_RT_SCANOUT_MAX = TgARRAY_COUNT(KTgKN_GPU_EXT_FORMAT_RT_SCANOUT) };

static const ETgKN_GPU_EXT_FORMAT KTgKN_GPU_EXT_FORMAT_DS_SCANOUT[] =  {
    ETgKN_GPU_EXT_FORMAT_D32_SFLOAT,
    ETgKN_GPU_EXT_FORMAT_D32_SFLOAT_S8_UINT,
    ETgKN_GPU_EXT_FORMAT_D24_UNORM_S8_UINT,
};
enum { KTgKN_GPU_EXT_FORMAT_DS_SCANOUT_MAX = TgARRAY_COUNT(KTgKN_GPU_EXT_FORMAT_DS_SCANOUT) };

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_MS__00,               ETgKN_GPU_MS__02,               ETgKN_GPU_MS__03,               ETgKN_GPU_MS__04,               ETgKN_GPU_MS__05,
    ETgKN_GPU_MS__06,               ETgKN_GPU_MS__07,               ETgKN_GPU_MS__08,               ETgKN_GPU_MS__09,               ETgKN_GPU_MS__10,
    ETgKN_GPU_MS__11,               ETgKN_GPU_MS__12,               ETgKN_GPU_MS__13,               ETgKN_GPU_MS__14,               ETgKN_GPU_MS__15,
    ETgKN_GPU_MS__16,
} ETgKN_GPU_MS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_MS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DOS_FONT_ROM_START = 0,

    ETgKN_GPU_DOS_FONT_ROM_DEFAULT = ETgKN_GPU_DOS_FONT_ROM_START,
    ETgKN_GPU_DOS_FONT_ROM_FUTURE,
    ETgKN_GPU_DOS_FONT_ROM_BLOCK,
    ETgKN_GPU_DOS_FONT_ROM_MARCIO,

    ETgKN_GPU_DOS_FONT_ROM_END,
    ETgKN_GPU_DOS_FONT_ROM_MAX = ETgKN_GPU_DOS_FONT_ROM_END,
    ETgKN_GPU_DOS_FONT_ROM_COUNT = ETgKN_GPU_DOS_FONT_ROM_END - ETgKN_GPU_DOS_FONT_ROM_START,
} ETgKN_GPU_DOS_FONT_ROM;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DOS_FONT_ROM);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DEBUG_PM_START = 0,

    ETgKN_GPU_DEBUG_PM_UNKNOWN = ETgKN_GPU_DEBUG_PM_START,

    ETgKN_GPU_DEBUG_PM_LN_START,
    ETgKN_GPU_DEBUG_PM_LN_LINE = ETgKN_GPU_DEBUG_PM_LN_START,
    ETgKN_GPU_DEBUG_PM_LN_AXES,
    ETgKN_GPU_DEBUG_PM_LN_FRUSTUM,
    ETgKN_GPU_DEBUG_PM_LN_PARABOLA,
    ETgKN_GPU_DEBUG_PM_LN_TETRAHEDRON,
    ETgKN_GPU_DEBUG_PM_LN_END,

    ETgKN_GPU_DEBUG_PM_2D_START = ETgKN_GPU_DEBUG_PM_LN_END,
    ETgKN_GPU_DEBUG_PM_2D_NGON = ETgKN_GPU_DEBUG_PM_2D_START,
    ETgKN_GPU_DEBUG_PM_2D_END,

    ETgKN_GPU_DEBUG_PM_3D_START = ETgKN_GPU_DEBUG_PM_2D_END,
    ETgKN_GPU_DEBUG_PM_3D_BOX = ETgKN_GPU_DEBUG_PM_3D_START,
    ETgKN_GPU_DEBUG_PM_3D_CAPSULE_CAP_0,
    ETgKN_GPU_DEBUG_PM_3D_CAPSULE_CAP_1,
    ETgKN_GPU_DEBUG_PM_3D_CAPSULE_TUBE,
    ETgKN_GPU_DEBUG_PM_3D_CONE,
    ETgKN_GPU_DEBUG_PM_3D_CYLINDER,
    ETgKN_GPU_DEBUG_PM_3D_PLANE,
    ETgKN_GPU_DEBUG_PM_3D_SPHERE,
    ETgKN_GPU_DEBUG_PM_3D_TUBE,
    ETgKN_GPU_DEBUG_PM_3D_END,

    ETgKN_GPU_DEBUG_PM_END = ETgKN_GPU_DEBUG_PM_3D_END,
    ETgKN_GPU_DEBUG_PM_MAX = ETgKN_GPU_DEBUG_PM_END,
    ETgKN_GPU_DEBUG_PM_COUNT = ETgKN_GPU_DEBUG_PM_END - ETgKN_GPU_DEBUG_PM_START,
    ETgKN_GPU_DEBUG_PM_LN_COUNT = ETgKN_GPU_DEBUG_PM_LN_END - ETgKN_GPU_DEBUG_PM_LN_START,
    ETgKN_GPU_DEBUG_PM_2D_COUNT = ETgKN_GPU_DEBUG_PM_2D_END - ETgKN_GPU_DEBUG_PM_2D_START,
    ETgKN_GPU_DEBUG_PM_3D_COUNT = ETgKN_GPU_DEBUG_PM_3D_END - ETgKN_GPU_DEBUG_PM_3D_START,
} ETgKN_GPU_DEBUG_PM;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DEBUG_PM);


/* ---- GPU - Resource - Defaults ------------------------------------------------------------------------------------------------------------------------------------------------ */

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_BLEND_STATE_START = 0,

    ETgKN_GPU_BLEND_STATE_NONE = ETgKN_GPU_BLEND_STATE_START,
    ETgKN_GPU_BLEND_STATE_ALPHA,
    ETgKN_GPU_BLEND_STATE_ALPHA_PREMULT,
    ETgKN_GPU_BLEND_STATE_ADDITIVE,

    ETgKN_GPU_BLEND_STATE_END,
    ETgKN_GPU_BLEND_STATE_MAX = ETgKN_GPU_BLEND_STATE_END,
    ETgKN_GPU_BLEND_STATE_COUNT = ETgKN_GPU_BLEND_STATE_END - ETgKN_GPU_BLEND_STATE_START,
} ETgKN_GPU_BLEND_STATE;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_BLEND_STATE);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_RASTERIZER_STATE_START = 0,

    ETgKN_GPU_RASTERIZER_STATE_DEFAULT_SOLID = ETgKN_GPU_RASTERIZER_STATE_START,
    ETgKN_GPU_RASTERIZER_STATE_DEFAULT_SOLID_LINE_AA,
    ETgKN_GPU_RASTERIZER_STATE_DEFAULT_WIREFRAME,

    ETgKN_GPU_RASTERIZER_STATE_END,
    ETgKN_GPU_RASTERIZER_STATE_MAX = ETgKN_GPU_RASTERIZER_STATE_END,
    ETgKN_GPU_RASTERIZER_STATE_COUNT = ETgKN_GPU_RASTERIZER_STATE_END - ETgKN_GPU_RASTERIZER_STATE_START,
} ETgKN_GPU_RASTERIZER_STATE;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_RASTERIZER_STATE);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DEPTH_STENCIL_STATE_START = 0,

    ETgKN_GPU_DEPTH_STENCIL_STATE_TEST_NONE = ETgKN_GPU_DEPTH_STENCIL_STATE_START,
    ETgKN_GPU_DEPTH_STENCIL_STATE_TEST_DEPTH,
    ETgKN_GPU_DEPTH_STENCIL_STATE_TEST_DEPTH_STENCIL,
    ETgKN_GPU_DEPTH_STENCIL_STATE_TEST_DEPTH_TRANSPARENT,
    ETgKN_GPU_DEPTH_STENCIL_STATE_TEST_DEPTH_TRANSPARENT_STENCIL,
    ETgKN_GPU_DEPTH_STENCIL_STATE_TEST_DEPTH_SHADOW_MAP,
    ETgKN_GPU_DEPTH_STENCIL_STATE_TEST_STENCIL,

    ETgKN_GPU_DEPTH_STENCIL_STATE_END,
    ETgKN_GPU_DEPTH_STENCIL_STATE_MAX = ETgKN_GPU_DEPTH_STENCIL_STATE_END,
    ETgKN_GPU_DEPTH_STENCIL_STATE_COUNT = ETgKN_GPU_DEPTH_STENCIL_STATE_END - ETgKN_GPU_DEPTH_STENCIL_STATE_START,
} ETgKN_GPU_DEPTH_STENCIL_STATE;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DEPTH_STENCIL_STATE);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_VS_START = 0,

    ETgKN_GPU_SHADER_VS_PARTICLE_SC_VWC_00 = ETgKN_GPU_SHADER_VS_START,
    ETgKN_GPU_SHADER_VS_PARTICLE_SC_VWC_01,
    ETgKN_GPU_SHADER_VS_TEST_SN_VWNC,

    ETgKN_GPU_SHADER_VS_END,
    ETgKN_GPU_SHADER_VS_MAX = ETgKN_GPU_SHADER_VS_END,
    ETgKN_GPU_SHADER_VS_COUNT = ETgKN_GPU_SHADER_VS_END - ETgKN_GPU_SHADER_VS_START,

} ETgKN_GPU_SHADER_VS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_VS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_TCS_START = 0,

    ETgKN_GPU_SHADER_TCS_END = ETgKN_GPU_SHADER_TCS_START,
    ETgKN_GPU_SHADER_TCS_MAX = ETgKN_GPU_SHADER_TCS_END,
    ETgKN_GPU_SHADER_TCS_COUNT = ETgKN_GPU_SHADER_TCS_END - ETgKN_GPU_SHADER_TCS_START,

} ETgKN_GPU_SHADER_TCS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_TCS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_TES_START = 0,

    ETgKN_GPU_SHADER_TES_END = ETgKN_GPU_SHADER_TES_START,
    ETgKN_GPU_SHADER_TES_MAX = ETgKN_GPU_SHADER_TES_END,
    ETgKN_GPU_SHADER_TES_COUNT = ETgKN_GPU_SHADER_TES_END - ETgKN_GPU_SHADER_TES_START,

} ETgKN_GPU_SHADER_TES;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_TES);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_GS_START = 0,

    ETgKN_GPU_SHADER_GS_END = ETgKN_GPU_SHADER_GS_START,
    ETgKN_GPU_SHADER_GS_MAX = ETgKN_GPU_SHADER_GS_END,
    ETgKN_GPU_SHADER_GS_COUNT = ETgKN_GPU_SHADER_GS_END - ETgKN_GPU_SHADER_GS_START,

} ETgKN_GPU_SHADER_GS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_GS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_TS_START = 0,

    ETgKN_GPU_SHADER_TS_END = ETgKN_GPU_SHADER_TS_START,
    ETgKN_GPU_SHADER_TS_MAX = ETgKN_GPU_SHADER_TS_END,
    ETgKN_GPU_SHADER_TS_COUNT = ETgKN_GPU_SHADER_TS_END - ETgKN_GPU_SHADER_TS_START,

} ETgKN_GPU_SHADER_TS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_TS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_MS_START = 0,

    ETgKN_GPU_SHADER_MS_END = ETgKN_GPU_SHADER_MS_START,
    ETgKN_GPU_SHADER_MS_MAX = ETgKN_GPU_SHADER_MS_END,
    ETgKN_GPU_SHADER_MS_COUNT = ETgKN_GPU_SHADER_MS_END - ETgKN_GPU_SHADER_MS_START,

} ETgKN_GPU_SHADER_MS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_MS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_FS_START = 0,

    ETgKN_GPU_SHADER_FS_PARTICLE_VWC = ETgKN_GPU_SHADER_FS_START,
    ETgKN_GPU_SHADER_FS_TEST_VWNC,

    ETgKN_GPU_SHADER_FS_END,
    ETgKN_GPU_SHADER_FS_MAX = ETgKN_GPU_SHADER_FS_END,
    ETgKN_GPU_SHADER_FS_COUNT = ETgKN_GPU_SHADER_FS_END - ETgKN_GPU_SHADER_FS_START,

} ETgKN_GPU_SHADER_FS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_FS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_SHADER_CS_START = 0,

    ETgKN_GPU_SHADER_CS_COLOUR_CORRECTION = ETgKN_GPU_SHADER_CS_START,
    ETgKN_GPU_SHADER_CS_LUMINANCE_HISTOGRAM,

    ETgKN_GPU_SHADER_CS_END,
    ETgKN_GPU_SHADER_CS_MAX = ETgKN_GPU_SHADER_CS_END,
    ETgKN_GPU_SHADER_CS_COUNT = ETgKN_GPU_SHADER_CS_END - ETgKN_GPU_SHADER_CS_START,

} ETgKN_GPU_SHADER_CS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_SHADER_CS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_INPUT_LAYOUT_START = 0,

    #define RENDER_INPUT_LAYOUT_PER_VERTEX(A, B, C, D, E, F, G, ...)
    #define RENDER_INPUT_LAYOUT_PER_VERTEX_APPEND(A, B, C, D, E, F, G, ...)
    #define RENDER_INPUT_LAYOUT_END(A)
    #define RENDER_INPUT_ALIGNMENT_CHECK(A,B)

    #define RENDER_INPUT_LAYOUT_START_FIRST(A,B) ETgKN_GPU_INPUT_LAYOUT_##B = ETgKN_GPU_INPUT_LAYOUT_START,
    #define RENDER_INPUT_LAYOUT_START(A,B) ETgKN_GPU_INPUT_LAYOUT_##B,
    #include "TgS KERNEL/TgS Kernel [GPU] - Resource [HLSL] [Vertex] [INC].h"
    #undef RENDER_INPUT_LAYOUT_START
    #undef RENDER_INPUT_LAYOUT_START_FIRST

    #define RENDER_INPUT_LAYOUT_START(A,B) ETgKN_GPU_INPUT_LAYOUT_INSTANCE_##B,
    #include "TgS KERNEL/TgS Kernel [GPU] - Resource [HLSL] [Vertex] [INC].h"
    #undef RENDER_INPUT_LAYOUT_START

    #undef RENDER_INPUT_ALIGNMENT_CHECK
    #undef RENDER_INPUT_LAYOUT_END
    #undef RENDER_INPUT_LAYOUT_PER_VERTEX_APPEND
    #undef RENDER_INPUT_LAYOUT_PER_VERTEX

    ETgKN_GPU_INPUT_LAYOUT_END,
    ETgKN_GPU_INPUT_LAYOUT_MAX = ETgKN_GPU_INPUT_LAYOUT_END,
    ETgKN_GPU_INPUT_LAYOUT_COUNT = ETgKN_GPU_INPUT_LAYOUT_END - ETgKN_GPU_INPUT_LAYOUT_START,

} ETgKN_GPU_INPUT_LAYOUT;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_INPUT_LAYOUT);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_PIPELINE_LAYOUT_START = 0,

    ETgKN_GPU_PIPELINE_LAYOUT__UNIT_TEST = ETgKN_GPU_PIPELINE_LAYOUT_START,
    ETgKN_GPU_PIPELINE_LAYOUT__POST_PROCESS_COMPUTE,

    ETgKN_GPU_PIPELINE_LAYOUT_END,
    ETgKN_GPU_PIPELINE_LAYOUT_MAX = ETgKN_GPU_PIPELINE_LAYOUT_END,
    ETgKN_GPU_PIPELINE_LAYOUT_COUNT = ETgKN_GPU_PIPELINE_LAYOUT_END - ETgKN_GPU_PIPELINE_LAYOUT_START,
} ETgKN_GPU_PIPELINE_LAYOUT;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_PIPELINE_LAYOUT);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_GRAPHICS_PIPELINE_START = 0,

    /* Unit Test */
    ETgKN_GPU_GRAPHICS_PIPELINE_UNIT_TEST_SCENE = ETgKN_GPU_GRAPHICS_PIPELINE_START,

    /* 3D Default Render Pass Test */
    ETgKN_GPU_GRAPHICS_PIPELINE_PARTICLE_00,
    ETgKN_GPU_GRAPHICS_PIPELINE_PARTICLE_01,

    ETgKN_GPU_GRAPHICS_PIPELINE_END,
    ETgKN_GPU_GRAPHICS_PIPELINE_MAX = ETgKN_GPU_GRAPHICS_PIPELINE_END,
    ETgKN_GPU_GRAPHICS_PIPELINE_COUNT = ETgKN_GPU_GRAPHICS_PIPELINE_END - ETgKN_GPU_GRAPHICS_PIPELINE_START,
} ETgKN_GPU_GRAPHICS_PIPELINE;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_GRAPHICS_PIPELINE);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_START = 0,

    ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_COLOUR_CORRECTION = ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_START,
    ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_LUMINANCE_HISTOGRAM,

    ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_END,
    ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_MAX = ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_END,
    ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_COUNT = ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_END - ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING_START,

} ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_COMPUTE_PIPELINE_FOR_RENDERING);

#include "TgS KERNEL/TgS Kernel [GPU] - Resource [HLSL] [Constants].h"

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_HLSL_COLOUR_SPACE_START = KTgMACRO_KN_GPU_HLSL_COLOR_SPACE_G22_P709,

    ETgKN_GPU_HLSL_COLOUR_SPACE_UNKNOWN = - 1,
    ETgKN_GPU_HLSL_COLOUR_SPACE_G22_P709 = KTgMACRO_KN_GPU_HLSL_COLOR_SPACE_G22_P709,
    ETgKN_GPU_HLSL_COLOUR_SPACE_G2084_P2020 = KTgMACRO_KN_GPU_HLSL_COLOR_SPACE_G2084_P2020,
    ETgKN_GPU_HLSL_COLOUR_SPACE_G10_P709 = KTgMACRO_KN_GPU_HLSL_COLOR_SPACE_G10_P709,
    ETgKN_GPU_HLSL_COLOUR_SPACE_G10_P709_NO_CORRECTION = KTgMACRO_KN_GPU_HLSL_COLOR_SPACE_G10_P709_NO_CORRECTION,

    ETgKN_GPU_HLSL_COLOUR_SPACE_END,
    ETgKN_GPU_HLSL_COLOUR_SPACE_MAX = ETgKN_GPU_HLSL_COLOUR_SPACE_END,
    ETgKN_GPU_HLSL_COLOUR_SPACE_COUNT = ETgKN_GPU_HLSL_COLOUR_SPACE_END - ETgKN_GPU_HLSL_COLOUR_SPACE_START,
} ETgKN_GPU_HLSL_COLOUR_SPACE;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_HLSL_COLOUR_SPACE);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DEFAULT_SAMPLER_START = 0,

    ETgKN_GPU_DEFAULT_SAMPLER__NEAREST_REPEAT = ETgKN_GPU_DEFAULT_SAMPLER_START,
    ETgKN_GPU_DEFAULT_SAMPLER__NEAREST_CLAMP,
    ETgKN_GPU_DEFAULT_SAMPLER__LINEAR_REPEAT,
    ETgKN_GPU_DEFAULT_SAMPLER__LINEAR_CLAMP,
    ETgKN_GPU_DEFAULT_SAMPLER__SHADOW,
    ETgKN_GPU_DEFAULT_SAMPLER__CUBEMAP,
    ETgKN_GPU_DEFAULT_SAMPLER__MIRROR_REPEAT,
    ETgKN_GPU_DEFAULT_SAMPLER__HIGH_QUALITY_ANISOTROPIC,

    ETgKN_GPU_DEFAULT_SAMPLER_END,
    ETgKN_GPU_DEFAULT_SAMPLER_MAX = ETgKN_GPU_DEFAULT_SAMPLER_END,
    ETgKN_GPU_DEFAULT_SAMPLER_COUNT = ETgKN_GPU_DEFAULT_SAMPLER_END - ETgKN_GPU_DEFAULT_SAMPLER_START,
} ETgKN_GPU_DEFAULT_SAMPLER;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DEFAULT_SAMPLER);
TgCOMPILER_ASSERT(KTgMACRO_KN_GPU_VLKN_SAMPLER_COUNT == ETgKN_GPU_DEFAULT_SAMPLER_COUNT, 0);

typedef enum TgATTRIBUTE_ENUM_FLAG
{
    ETgKN_GPU_EXT_COMMAND_NONE = -1,
    ETgKN_GPU_EXT_COMMAND_UNKNOWN = ETgKN_GPU_EXT_COMMAND_NONE,

    ETgKN_GPU_EXT_COMMAND_START = 0,

    ETgKN_GPU_EXT_COMMAND_GRAPHICS = ETgKN_GPU_EXT_COMMAND_START,
    ETgKN_GPU_EXT_COMMAND_PRESENT,
    ETgKN_GPU_EXT_COMMAND_COMPUTE,
    ETgKN_GPU_EXT_COMMAND_TRANSFER,

    ETgKN_GPU_EXT_COMMAND_END,
    ETgKN_GPU_EXT_COMMAND_MAX = ETgKN_GPU_EXT_COMMAND_END,
    ETgKN_GPU_EXT_COMMAND_COUNT = ETgKN_GPU_EXT_COMMAND_END - ETgKN_GPU_EXT_COMMAND_START,
} ETgKN_GPU_EXT_COMMAND;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_EXT_COMMAND);




/* -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.--.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-. */
/*  Public Debug Constants                                                                                                                                                         */
/* -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.--.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-. */

#if defined(TgCOMPILE__RENDER_DEBUG_OUTPUT)
enum { KTgKN_GPU_MAX_DBG_STORAGE_TEXT              =   16384,   /**< Maximum number of glyphs in a single frame. */
       KTgKN_GPU_MAX_DBG_STORAGE_GEOM_INSTANCE     =   16384,   /**< Maximum number of geometry instances in a single frame. */
       KTgKN_GPU_MAX_DBG_STORAGE_LINE              = 1048576,   /**< Maximum number of lines in a single frame. */
       KTgKN_GPU_MAX_DBG_LINE_DRAW                 =     128,   /**< Maximum number of line draws in a single frame. */
};

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DBG_SHADER_VS_START = 0,

    ETgKN_GPU_DBG_SHADER_VS_VERTEX_GEOM_S_VW = ETgKN_GPU_DBG_SHADER_VS_START,
    ETgKN_GPU_DBG_SHADER_VS_VERTEX_GEOM_SC_VWC,
    ETgKN_GPU_DBG_SHADER_VS_VERTEX_GEOM_SN_VWNC,
    ETgKN_GPU_DBG_SHADER_VS_VERTEX_GEOM_SNC_VWNC,
    ETgKN_GPU_DBG_SHADER_VS_VERTEX_UI_SUC_UC,
    ETgKN_GPU_DBG_SHADER_VS_VERTEX_TEXT_SU_U,
    ETgKN_GPU_DBG_SHADER_VS_VERTEX_GEOM_SN_VWNC_I,

    ETgKN_GPU_DBG_SHADER_VS_END,
    ETgKN_GPU_DBG_SHADER_VS_MAX = ETgKN_GPU_DBG_SHADER_VS_END,
    ETgKN_GPU_DBG_SHADER_VS_COUNT = ETgKN_GPU_DBG_SHADER_VS_END - ETgKN_GPU_DBG_SHADER_VS_START,

} ETgKN_GPU_DBG_SHADER_VS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DBG_SHADER_VS);

enum { ETgKN_GPU_DBG_SHADER_TCS_END = 0 };
enum { ETgKN_GPU_DBG_SHADER_TES_END = 0 };
enum { ETgKN_GPU_DBG_SHADER_GS_END = 0 };

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DBG_SHADER_TS_START = 0,

    ETgKN_GPU_DBG_SHADER_TS_LINE = ETgKN_GPU_DBG_SHADER_TS_START,

    ETgKN_GPU_DBG_SHADER_TS_END,
    ETgKN_GPU_DBG_SHADER_TS_MAX = ETgKN_GPU_DBG_SHADER_TS_END,
    ETgKN_GPU_DBG_SHADER_TS_COUNT = ETgKN_GPU_DBG_SHADER_TS_END - ETgKN_GPU_DBG_SHADER_TS_START,

} ETgKN_GPU_DBG_SHADER_TS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DBG_SHADER_TS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DBG_SHADER_MS_START = 0,

    ETgKN_GPU_DBG_SHADER_MS_LINE = ETgKN_GPU_DBG_SHADER_MS_START,

    ETgKN_GPU_DBG_SHADER_MS_END,
    ETgKN_GPU_DBG_SHADER_MS_MAX = ETgKN_GPU_DBG_SHADER_MS_END,
    ETgKN_GPU_DBG_SHADER_MS_COUNT = ETgKN_GPU_DBG_SHADER_MS_END - ETgKN_GPU_DBG_SHADER_MS_START,

} ETgKN_GPU_DBG_SHADER_MS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DBG_SHADER_MS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DBG_SHADER_FS_START = 0,

    ETgKN_GPU_DBG_SHADER_FS_LINE = ETgKN_GPU_DBG_SHADER_FS_START,
    ETgKN_GPU_DBG_SHADER_FS_VW,
    ETgKN_GPU_DBG_SHADER_FS_VWC_00,
    ETgKN_GPU_DBG_SHADER_FS_VWC_01, /* With Gamma Correction */
    ETgKN_GPU_DBG_SHADER_FS_VWNC,
    ETgKN_GPU_DBG_SHADER_FS_UC_00,
    ETgKN_GPU_DBG_SHADER_FS_UC_01, /* With Gamma Correction */
    ETgKN_GPU_DBG_SHADER_FS_TEXT_U,

    ETgKN_GPU_DBG_SHADER_FS_END,
    ETgKN_GPU_DBG_SHADER_FS_MAX = ETgKN_GPU_DBG_SHADER_FS_END,
    ETgKN_GPU_DBG_SHADER_FS_COUNT = ETgKN_GPU_DBG_SHADER_FS_END - ETgKN_GPU_DBG_SHADER_FS_START,

} ETgKN_GPU_DBG_SHADER_FS;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DBG_SHADER_FS);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_START = 0,

    /* 2D (Screen) Default Debug PSO */
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_UI = ETgKN_GPU_DBG_GRAPHICS_PIPELINE_START,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_UI_WITH_GAMMA,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_TEXT,

    /* 3D Default Debug PSO */
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_LINE_TASK_MESH,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_00,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_01,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_01_WITH_GAMMA,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_02,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_02_INSTANCE,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_02_LIT,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_02_LIT_INSTANCE,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_GEOM_03,

    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_END,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_MAX = ETgKN_GPU_DBG_GRAPHICS_PIPELINE_END,
    ETgKN_GPU_DBG_GRAPHICS_PIPELINE_COUNT = ETgKN_GPU_DBG_GRAPHICS_PIPELINE_END - ETgKN_GPU_DBG_GRAPHICS_PIPELINE_START,
} ETgKN_GPU_DBG_GRAPHICS_PIPELINE;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DBG_GRAPHICS_PIPELINE);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DBG_COMPUTE_PIPELINE_START = 0,

    ETgKN_GPU_DBG_COMPUTE_PIPELINE_END = ETgKN_GPU_DBG_COMPUTE_PIPELINE_START,
    ETgKN_GPU_DBG_COMPUTE_PIPELINE_MAX = ETgKN_GPU_DBG_COMPUTE_PIPELINE_END,
    ETgKN_GPU_DBG_COMPUTE_PIPELINE_COUNT = ETgKN_GPU_DBG_COMPUTE_PIPELINE_END - ETgKN_GPU_DBG_COMPUTE_PIPELINE_START,

} ETgKN_GPU_DBG_COMPUTE_PIPELINE;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DBG_COMPUTE_PIPELINE);

typedef enum TgATTRIBUTE_ENUM
{
    ETgKN_GPU_DBG_PIPELINE_LAYOUT_START = 0,

    ETgKN_GPU_DBG_PIPELINE_LAYOUT__NONE = ETgKN_GPU_DBG_PIPELINE_LAYOUT_START,
    ETgKN_GPU_DBG_PIPELINE_LAYOUT__UBO,
    ETgKN_GPU_DBG_PIPELINE_LAYOUT__SBO,
    ETgKN_GPU_DBG_PIPELINE_LAYOUT__LINE_TASK_MESH,

    ETgKN_GPU_DBG_PIPELINE_LAYOUT_END,
    ETgKN_GPU_DBG_PIPELINE_LAYOUT_MAX = ETgKN_GPU_DBG_PIPELINE_LAYOUT_END,
    ETgKN_GPU_DBG_PIPELINE_LAYOUT_COUNT = ETgKN_GPU_DBG_PIPELINE_LAYOUT_END - ETgKN_GPU_DBG_PIPELINE_LAYOUT_START,
} ETgKN_GPU_DBG_PIPELINE_LAYOUT;
TgTYPE_MODIFIER_DEFAULT(ETgKN_GPU_DBG_PIPELINE_LAYOUT);

/*# defined(TgCOMPILE__RENDER_DEBUG_OUTPUT) */
#endif



/* =============================================================================================================================================================================== */
#endif
