# 015482FC-A4BD-4E1C-AE49-A30E5728D73A
CMAKE_MINIMUM_REQUIRED(VERSION 3.31)
CMAKE_POLICY(VERSION 3.31)


# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ #
# SETUP

MESSAGE (DEBUG "========================================================================================================================")
MESSAGE (DEBUG "= CONFIG REPORT                                                                                                        =")
MESSAGE (DEBUG "========================================================================================================================")
MESSAGE (DEBUG "=       GIT EXECUTABLE: ${GIT_EXECUTABLE}")
MESSAGE (DEBUG "")
MESSAGE (DEBUG "=   EXTERNAL BUILD DIR: ${MK_BUILD__EXTERNAL_BUILD_DIRECTORY}")
MESSAGE (DEBUG "= EXTERNAL INSTALL DIR: ${MK_BUILD__EXTERNAL_INSTALL_DIRECTORY}")
MESSAGE (DEBUG "=            BUILD DIR: ${MK_BUILD__BUILD_DIRECTORY}")
MESSAGE (DEBUG "=          INSTALL DIR: ${MK_BUILD__INSTALL_DIRECTORY}")
MESSAGE (DEBUG "=            BUILD DIR: ${CMAKE_BINARY_DIR}")
MESSAGE (DEBUG "")
MESSAGE (DEBUG "=  EXTERNAL BUILD TYPE: ${CMAKE_BUILD_TYPE_EXTERNAL}")
MESSAGE (DEBUG "=       MK_BUILD__LIST: ${MK_BUILD__LIST}")
MESSAGE (DEBUG "")
MESSAGE (DEBUG "=           C COMPILER: ${CMAKE_C_COMPILER}")
MESSAGE (DEBUG "=              C FLAGS: ${CMAKE_C_FLAGS}")
MESSAGE (DEBUG "=        C FLAGS DEBUG: ${CMAKE_C_FLAGS_DEBUG}")
MESSAGE (DEBUG "=      C FLAGS RELEASE: ${CMAKE_C_FLAGS_RELEASE}")
MESSAGE (DEBUG "=     C FLAGS EXTERNAL: ${CMAKE_C_FLAGS_FOR_EXTERNAL_PROJECTS}")
MESSAGE (DEBUG "")
MESSAGE (DEBUG "=         CXX COMPILER: ${CMAKE_CXX_COMPILER}")
MESSAGE (DEBUG "=            CXX FLAGS: ${CMAKE_CXX_FLAGS}")
MESSAGE (DEBUG "=      CXX FLAGS DEBUG: ${CMAKE_CXX_FLAGS_DEBUG}")
MESSAGE (DEBUG "=    CXX FLAGS RELEASE: ${CMAKE_CXX_FLAGS_RELEASE}")
MESSAGE (DEBUG "=   CXX FLAGS EXTERNAL: ${CMAKE_CXX_FLAGS_FOR_EXTERNAL_PROJECTS}")
MESSAGE (STATUS "========================================================================================================================")
MESSAGE (STATUS "=  DEBUG PROJECT NAME: ${MK_TEIKITU_PROJECT_NAME} / ${MK_PROJECT_NAME}")
MESSAGE (STATUS "=         PROJECT IDE: ${MK_BUILD__IDE_NAME} [GENERATOR: ${CMAKE_GENERATOR}]")
MESSAGE (STATUS "=                HOST: ${MK_BUILD__HOST_NAME} [HOST: ${CMAKE_HOST_SYSTEM_NAME}]")
MESSAGE (STATUS "=   COMPILER FRONTEND: C|CXX: ${MK_BUILD__COMPILER_FRONTEND_NAME} [C:${CMAKE_C_COMPILER_FRONTEND_VARIANT}, CXX: ${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}]")
MESSAGE (STATUS "=    COMPILER BACKEND: C|CXX: ${MK_BUILD__COMPILER_NAME} [C:${CMAKE_C_COMPILER_ID}, CXX: ${CMAKE_CXX_COMPILER_ID}]")
MESSAGE (STATUS "=              TARGET: ${MK_COMPILE__TYPE}")
MESSAGE (STATUS "=            HARDWARE: ${MK_BUILD__HARDWARE_NAME}")
MESSAGE (STATUS "=              THREAD: ${MK_BUILD__THREAD_NAME}")
MESSAGE (STATUS "=           UNIVERSAL: ${MK_BUILD__UNIVERSAL_NAME}")
MESSAGE (STATUS "=                  OS: ${MK_BUILD__OS_NAME}")
MESSAGE (STATUS "=              DEVICE: ${MK_BUILD__DEVICE_NAME}")
IF (MK_BUILD__OS_TEXT_WIDE)
    MESSAGE (STATUS "=       PLATFORM TEXT: WIDE")
ELSE ()
    MESSAGE (STATUS "=       PLATFORM TEXT: UTF8")
ENDIF ()
MESSAGE (STATUS "=  FEATURE (GRAPHICS): ${MK_BUILD__GRAPHICS_NAME}")
MESSAGE (STATUS "=     FEATURE (AUDIO): ${MK_BUILD__AUDIO_NAME}")
MESSAGE (STATUS "========================================================================================================================")
