name: Tools
run-name: "Ninja-WIN-REF-None-C17-WIN-WIN-X64-TOOLS"
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/configure__github_runner_image_runtime.yml
    with:
      os: windows-latest
      cmake_command: -VERBOSE -CICD_BUILD -TEIKITU -IDE:NINJA -COMPILER:CLANG -THREAD:WINDOWS -OS:WINDOWS -DEVICE:DESKTOP -CPU:C17_X64 -GPU:REF -BUILD_TYPE:TOOLS
    secrets: inherit
